### ISSUE TITLE
Error with Webdriver and xpath expression

### ISSUE THREAD

**Issue by david-vendel** [haxtivitiez/AutomateSendingFbMessengerToAllFriends#1]
Hey, I have a problem probably locating firefox.exe, even when I changed Program Files for x86 one.. I use Win10
`Traceback (most recent call last):
  File "as.py", line 75, in <module>
    fox.AutomateFox()
  File "as.py", line 12, in AutomateFox
    driver = webdriver.Firefox(firefox_binary=binary)
  File "C:\Users\David\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 152, in __init__
    self.service.start()
  File "C:\Users\David\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.`

**Comment by david-vendel** [comment]
OK I have solved this by adding Mozilla Firefox folder to PATH.

**Comment by david-vendel** [comment]
I have another issue now:
After sign up, it sais:

`Given xpath expression "XPATH SIGNATURE" is invalid: SyntaxError: The expression is not a legal expression.`
